########################################
## Macro Definition
########################################
DEBUG    = -O3#-g -pg
CC       = gcc
CFLAGS   = -Wall $(DEBUG)
CXX      = g++
CXXFLAGS = -Wall $(DEBUG)
LD       = gcc
LDFLAGS  = $(DEBUG)
INCLUDES = -I.
LIBS     = -lX11
RM       = rm -f
PROF     = gprof
TARGET   = xwarpptr
SRCS     = main.c
OBJS     = main.o

########################################
## Rules
########################################
.SUFFIXES:
.SUFFIXES: .c .cpp .o
.PHONY: all rebuild clean run profile
all: $(TARGET)
rebuild: clean $(TARGET)
clean:
	$(RM) $(TARGET) $(OBJS) gmon.out tags *~
run: $(TARGET)
	./$(TARGET)
profile:
	$(PROF) $(TARGET) gmon.out | less
$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<
.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $<

# Dependency(Generated by 'gcc -MM *.c')
main.o: main.c

